# 应用名称
spring:
  application:
    name: service-verification-code
  redis:
    port: 6379
    host: 192.168.177.101
# 应用服务 WEB 访问端口
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://eureka0:7900/eureka/
#    enabled: false
