# 应用名称
spring:
  application:
    name: cloud-zuul
#  redis:
#    port: 6379
#    host: 192.168.177.101
# 应用服务 WEB 访问端口
server:
  port: 9100
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://eureka0:7900/eureka/
    registry-fetch-interval-seconds: 30
  instance:
    lease-renewal-interval-in-seconds: 30
