spring:
  application:
    name: api-passenger
server:
  port: 8080
eureka:
  client:
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://localhost:7900/eureka/
      #,http://localhost:7901/eureka/,http://localhost:7902/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30