spring:
  # 应用名称
  application:
    name: service-user
  # 数据库驱动：
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源名称
    name: defaultDataSource
    username: root
    password: F@20dms2020
    url: jdbc:mysql://10.9.33.193:3306/test1
    # 连接池配置
    dbcp2:
      # 初始化连接数
      initial-size: 5
      # 最小维持连接数
      min-idle: 5
      # 最大连接数
      max-total: 5
      # 等待连接获取的最大超时时间
      max-wait-millis: 300
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  redis:
    port: 6379
    host: 192.168.177.101
# 应用服务 WEB 访问端口
server:
  port: 8081
#下面这些内容是为了让MyBatis映射
mybatis:
  #指定Mybatis的Mapper文件
  mapper-locations:
    - classpath:mappers/*xml
  #指定Mybatis的实体目录
  type-aliases-package: com.van.serviceuser.entity
eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://eureka0:7900/eureka/
    registry-fetch-interval-seconds: 30
  instance:
    lease-renewal-interval-in-seconds: 30




