# 应用名称
spring:
  application:
    name: cloud-hystrix-turbine
turbine:
  app-config: api-passenger
  cluster-name-expression: "'default'"
eureka:
  client:
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://localhost:7900/eureka/
      #,http://localhost:7901/eureka/,http://localhost:7902/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
